#printing colors
colors=["red","green","blue"]
for color in colors:
    print(color,end=" ")

#Print numbers from 1 to 10.
for i in range(10):
    print(i+1)

#Print the word “Hello World” 5 times.
word="Hello World"
for i in range(5):
    print(word)

#Print characters of the word "Python" one by one.
for i in "Python":
    print(i)

#Print all even numbers from 1 to 20.
for i in range(2, 21, 2):
    print(i)

#Print numbers from 10 to 1 in reverse order.
for i in range(10, 0, -1):
    print(i)

#Given a list of fruits, print each fruit on a new line.
fruits=["Apple","Berry","Banana","Kiwi"]
for fruit in fruits:
    print(fruit)

 



